# Generated by Django 3.1 on 2020-09-16 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 16, 5, 58, 44, 890284)),
        ),
        migrations.AddField(
            model_name='note',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 9, 16, 5, 58, 44, 890310)),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
